spring:
  datasource:
    url: jdbc:mysql://liukewensc.mysql.rds.aliyuncs.com:3306/dev_framework_demo
    username: kewen
    password: Lh19921002
    driver-class-name: com.kewen.framework.boot.basic.p6spy.KP6SpyDriver