spring:
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
    sentinel:
      transport:
        dashboard: "127.0.0.1:8801"
        port: 8719

feign:
  sentinel:
    enabled: true