server:
  port: 8082

spring:
  application:
    name: nocos-consumer-sample
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"

feign:
  sentinel:
    enabled: true