spring:
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


logging:
  level:
    org.springframework: debug
kewen:
  auth:
    login-endpoint: /login
    type: web   # security/web
    web:
      store:
        type: session # session/token