spring:
  profiles:
    active: dev


server:
  port: 8608
  servlet:
    context-path: /admin
logging:
  level:
    org.springframework: debug
kewen:
  auth:
    login-endpoint: /auth/login
    type: security   # security/web
    web:
      store:
        type: token # session/token
