spring:
  profiles:
    active: dev


logging:
  level:
    org.springframework: debug
kewen:
  auth:
    login-endpoint: /login
    type: security   # security/web
    web:
      store:
        type: token # session/token