server:
  port: 6100

kewen:
  framework:
    cloud:
      eureka:
        server:
          port: 7001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          lower-case-service-id: true # 忽略大小写
      routes:
        - id: web-portal            # 路由id
          uri: lb://web-portal      # 访问地址 应用名/跳转地址
          # uri: http://localhost:6900
          predicates :
            - Path=/web-portal/**  # 匹配规则
            #- Path=/getUser
          filters:                # 过滤器
            - StripPrefix=1       # 截取前缀
