spring:
  datasource:
    username: uucs
    password: UUCSuucs
    url: "jdbc:p6spy:mysql://liukewensc.mysql.rds.aliyuncs.com:3306/uucs"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
