spring:
  application:
    name: sample
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    driver-class-name: com.kewen.framework.boot.basic.p6spy.KP6SpyDriver
kewen:
  storage:
    type: qiniu
    access-key: your_qiniu_access_key
    secret-key: your_qiniu_secret_key
    bucket: your_bucket_name
    is-public: false
    download-domain: your_download_domain
    upload-callback-url: https://your_domain.com/storage/upload/callback
