kewen:
  storage:
    type: qiniu
    access-key: qYUhPA6FvZ29dQ4pz1BgLwHaTcV2vt_rD-GoEEFB
    secret-key: eyihg0gLAyHd2j08geDCCWdI0UHOfhxzpjFpKso1
    bucket: kewen-blog
    download-domain: rtk99wucl.hd-bkt.clouddn.com

spring:
  profiles:
    active: dev