spring:
  application:
    name: sample
  datasource:
    url: jdbc:mysql://liukewensc.mysql.rds.aliyuncs.com:3306/dev_framework_demo
    username: kewen
    password: Lh19921002
    driver-class-name: com.kewen.framework.boot.basic.p6spy.KP6SpyDriver
kewen:
  storage:
    type: qiniu
    access-key: qYUhPA6FvZ29dQ4pz1BgLwHaTcV2vt_rD-GoEEFB
    secret-key: eyihg0gLAyHd2j08geDCCWdI0UHOfhxzpjFpKso1
    bucket: kewen-storage
    is-public: false
    download-domain: storage.liukewen.cn
    upload-callback-url: https://33960819lh.oicp.vip/storage/upload/callback
