kewen:
  base:

    request:
      params-persistent: true  # 请求参数持久化开启
  storage:
    open-persistent: true
    type: qiniu
    access-key: qYUhPA6FvZ29dQ4pz1BgLwHaTcV2vt_rD-GoEEFB
    secret-key: eyihg0gLAyHd2j08geDCCWdI0UHOfhxzpjFpKso1
    bucket: kewen-storage
    download-domain: storage.liukewen.cn
    upload-callback-url: https://33960819lh.oicp.vip/storage/upload/callback


spring:
  profiles:
    active: dev

