spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework: debug
kewen:
  auth:
    login-endpoint: /auth/login
    logout-endpoint: /auth/logout
    permit-url: /auth/getWebSiteName;/hello/hello
    store:
      type: token
      expire-time: 1800