spring:
  profiles:
    active: dev


server:
  port: 8608
  servlet:
    context-path: /admin
logging:
  level:
    org.springframework: debug
kewen:
  auth:
    login-endpoint: /auth/login
    logout-endpoint: /auth/logout
    permit-url: /auth/getWebSiteName


#    web:
#      store:
#        type: session