spring:
  datasource:
    url: jdbc:mysql://liukewensc.mysql.rds.aliyuncs.com:3306/kewen_framework_auth_template
    username: open_framework
    password: framework123456_
    driver-class-name: com.kewen.framework.boot.basic.p6spy.KP6SpyDriver